services:

  db:
    image: postgres:latest
    container_name: uberto_sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./Docker/init_db.sh:/docker-entrypoint-initdb.d/01_init_db.sh

  mongo:
    image: mongo:latest
    container_name: uberto_mongo
    hostname: host-mongo
    ports:
      - "27019:27017"
    volumes:
      - ~/apps/uberto_mongo_db:/data/db
      - ~/apps/uberto_mongo_log:/var/log/mongodb/
      - ./Docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: uberto_mongo


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_uberto
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@phm.edu.ar
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
  pgadmin-data:

