version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: uberto_sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./Docker/init_db.sh:/docker-entrypoint-initdb.d/01_init_db.sh

  # Config servers
  configsvr1:
    image: mongo
    container_name: configsvr1
    command: mongod --configsvr --replSet configrs --port 27019
    ports:
      - 27019:27019
    volumes:
      - config1_data:/data/db

  configsvr2:
    image: mongo
    container_name: configsvr2
    command: mongod --configsvr --replSet configrs --port 27019
    volumes:
      - config2_data:/data/db

  configsvr3:
    image: mongo
    container_name: configsvr3
    command: mongod --configsvr --replSet configrs --port 27019
    volumes:
      - config3_data:/data/db

  # Shard 1
  shard1a:
    image: mongo
    container_name: shard1a
    command: mongod --shardsvr --replSet shard1rs --port 27018
    ports:
      - 27018:27018
    volumes:
      - shard1a_data:/data/db

  shard1b:
    image: mongo
    container_name: shard1b
    command: mongod --shardsvr --replSet shard1rs --port 27021
    volumes:
      - shard1b_data:/data/db

  shard1c:
    image: mongo
    container_name: shard1c
    command: mongod --shardsvr --replSet shard1rs --port 27022
    volumes:
      - shard1c_data:/data/db

  # Shard 2
  shard2a:
    image: mongo
    container_name: shard2a
    command: mongod --shardsvr --replSet shard2rs --port 27020
    ports:
      - 27020:27020
    volumes:
      - shard2a_data:/data/db

  shard2b:
    image: mongo
    container_name: shard2b
    command: mongod --shardsvr --replSet shard2rs --port 27023
    volumes:
      - shard2b_data:/data/db

  shard2c:
    image: mongo
    container_name: shard2c
    command: mongod --shardsvr --replSet shard2rs --port 27024
    volumes:
      - shard2c_data:/data/db

  # Mongos
  mongos:
    image: mongo
    container_name: mongos
    depends_on:
      - configsvr1
      - configsvr2
      - configsvr3
      - shard1a
      - shard1b
      - shard1c
      - shard2a
      - shard2b
      - shard2c
    ports:
      - 27017:27017
    command: >
      mongos --configdb configrs/configsvr1:27019,configsvr2:27019,configsvr3:27019 --bind_ip_all
    volumes:
      - ./Docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: uberto_mongo

  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_uberto
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@phm.edu.ar
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    container_name: redis-uberto
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander-uberto
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uberto-backend
    ports:
      - "4026:8080"
    depends_on:
      - mongos
      - redis
      - db


volumes:
  db:
  pgadmin-data:
  config1_data:
  config2_data:
  config3_data:
  shard1a_data:
  shard1b_data:
  shard1c_data:
  shard2a_data:
  shard2b_data:
  shard2c_data:


