spring:
    application:
        name: backend-grupo7-2025

    devtools:
        livereload:
            enabled: false

    datasource:
        url: jdbc:postgresql://localhost:5432/
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: create-drop

security:
    secret-key: 8bcc50a89968cd9dfb5f5421a1896dfe4b66a03082d3d47499739d4035a4be8b1fe791b8cd99358ceac4bf71fdaba730b9dd6d41011efa9b641429e3416f9d013b5496b62a1061b9312054db8ca566af70c3da6ad0a6877a6ea8bcce14dd1378
    access-token-minutes: 300
