spring:
  application:
    name: backend-grupo7-2025

  devtools:
    livereload:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  data:
    mongodb:
      uri: mongodb://mongo_app:mongo_app@127.0.0.1:27017/uberto_mongo?authSource=uberto_mongo
      # uri: mongodb://mongo:mongo@127.0.0.1:27019/uberto_mongo?authSource=admin
#  redis:
#    host: localhost
#    port: 6379
    password: ""  # Opcional
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2

  neo4j:
    #uri: neo4j+s://b67f6ce0.databases.neo4j.io
    uri: neo4j+s://d410fe7b.databases.neo4j.io
    authentication:
      username: neo4j
      #password: sI1xyOdR-sqojTjZrqhnTTMWq-K0EoH9-v0LAj7LDNc
      password: tUelEMVlcoMTul5Tp85MYqbnubMwhX14giQCyuUg3Uc


logging:
  level:
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: DEBUG

security:
  secret-key: cd372fb85148700fa88095e3492d3f9f5beb43e555e5ff26d95f5a6adc36f8e6
  access-token-minutes: 300

